### ISSUE TITLE
The problem with the calculation of the path to the fonts

### ISSUE THREAD

**Issue by khusamov** [devex-web-frontend/postcss-assets-rebase#8]
I have a problem with file paths.

Gulp task:

``` javascript
gulp.task("css", function () {
    let src = ["bower_components/bootswatch/united/bootstrap.css"];
    let options = { keepStructure: true, relative: true, assetsPath: "assets" };
    gulp.src(src)
        .pipe(postcss([assetsRebase(options)], { to: "public/build/all.css" }))
        .pipe(concatCss("all.css"))
        .pipe(gulp.dest("public/build"));
});
```

At the entrance to the file:

**bower_components/bootswatch/united/bootstrap.css:**

``` css
@font-face {
    src: url('../fonts/glyphicons-halflings-regular.eot');
}
```

The output is a file with an error (wrong path):

**public/build/all.css:**

``` css
@font-face {
    src: url("../../bootswatch/united/assets/bower_components/bootswatch/fonts/glyphicons-halflings-regular.eot");
}
```

And here I should get the file:

``` css
@font-face {
    src: url("assets/bower_components/bootswatch/fonts/glyphicons-halflings-regular.eot");
}
```

How do I configure a task so that the path to the font correctly calculated?
